# Generated by Django 5.0.7 on 2024-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_carrequest_descritpion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
