# Generated by Django 5.0.7 on 2024-08-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_alter_carrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrequest',
            old_name='descritpion',
            new_name='description',
        ),
    ]
