# Generated by Django 5.0.7 on 2024-08-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_department_staff_transportofficer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrequest',
            old_name='user',
            new_name='staff',
        ),
    ]
