# Generated by Django 5.0.7 on 2024-08-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_rename_user_carrequest_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures/'),
        ),
    ]
