# Generated by Django 5.0.7 on 2024-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0008_alter_carrequest_vehicle_alter_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
