# Generated by Django 5.0.7 on 2024-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_carrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
